import { createRef } from 'react';
import {
  BookmarkIconProfile,
  CopyLinkSvgIcon,
  FacebookSvgIcon,
  FollowersIcon,
  FollowingIcon,
  LinkedinSvgIcon,
  OverViewIcon,
  PlayProfileIcon,
  ProductDeliveredSvg,
  ProductOrderedSvg,
  ProductShippedSvg,
  ShopProfileIcon,
  TagListSvgIcon,
  TwitterSvgIcon,
  WhatsappSvgIcon,
  WishlistIcon,
} from '../assets/SVGs';
import { Dimensions, Platform } from 'react-native';
import { moderateScale } from 'react-native-size-matters';
import { getColors } from '../utility';

// KEEP DARK_THEME_COLORS, LIGHT_THEME_COLORS, DISPLAY_MODES, CURRENT_MODE AND GRADIENT_COLOR TWO TIME DUE TO GET_COLOR FUNCTION ISSUE

export const DARK_THEME_COLORS = {
  BLACK: '#121212',
  BLACK_2: '#141414',
  WHITE: '#FFFFFF',
  BLUE: '#188BFF',
  BLUE_2: '#127CE6',
  LIGHT_BLUE: '#76BAFF',
  DARK_BLUE: '#233241',
  GREY: '#B6BDCB',
  GREY_2: '#3C3B3B',
  GREY_3: '#666666',
  GREY_4: '#707070',
  GREY_5: 'ffffff4d',
  DARK_GREY: '#A6A6A6',
  PLACEHOLDER_BLACK: '#2D2D2F',
  INPUT_BACKGROUND_BLACK: '#1F1F1F',
  INPUT_BACKGROUND_BLACK_2: '#292929',
  INPUT_BACKGROUND_BLACK_3: '#3C3B3B',
  LIGHT_GREY: '#A7A7A7',
  LIGHT_GREY_1: '#757575',
  LIGHT_GREY_2: '#454545',
  RED: '#C31514',
  RED_2: '#FF0000',
  RED_3: '#FF0E0E',
  GREEN: '#34A043',
  DARK_GREEN: '#026440',
  LIGHT_GREEN: '#5EFF74',
  LIGHT_GREEN_2: '#34A043',
  DARK_GREY_2: '#3C3C3C68',
  LIGHT_BLACK: '#383737bd',
  ORANGE: '#FF7B30',
  YELLOW: '#FFDC00',
};

export const LIGHT_THEME_COLORS = {
  BLACK: '#121212',
  BLACK_2: '#141414',
  WHITE: '#FFFFFF',
  BLUE: '#188BFF',
  BLUE_2: '#127CE6',
  LIGHT_BLUE: '#76BAFF',
  GREY: '#B6BDCB',
  GREY_2: '#3C3B3B',
  GREY_3: '#666666',
  GREY_4: '#707070',
  GREY_5: 'ffffff4d',
  DARK_GREY: '#A6A6A6',
  DARK_GREY_3: '#8B8B8B',
  PLACEHOLDER_BLACK: '#2D2D2F',
  INPUT_BACKGROUND_BLACK: '#1F1F1F',
  INPUT_BACKGROUND_BLACK_2: '#292929',
  INPUT_BACKGROUND_BLACK_3: '#3C3B3B',
  LIGHT_GREY: '#A7A7A7',
  LIGHT_GREY_1: '#757575',
  LIGHT_GREY_2: '#454545',
  RED: '#C31514',
  RED_2: '#FF0000',
  GREEN: '#34A043',
  DARK_GREEN: '#026440',
  LIGHT_GREEN: '#5EFF74',
  DARK_GREY_2: '#3C3C3C68',
  LIGHT_BLACK: '#383737bd',
  ORANGE: '#FF7B30',
  YELLOW: '#FFDC00',
  RED_3: '#FF5252',
};

export const navigationRef = createRef();

export const DISPLAY_MODES = {
  DARK_MODE: 'dark_mode',
  LIGHT_MODE: 'light_mode',
};

export const CURRENT_MODE = 'dark_mode';
export const GRADIENT_COLOR = [
  '#000000',
  '#191919C0',
  '#3C3C3C68',
  '#FFFFFF00',
];

export const ALERTS = {
  AUTH: {
    ENTER_EMAIL: 'Please enter email',
    ENTER_VALID_EMAIL: 'Please enter valid email',
    ENTER_PASSWORD: 'Please enter password',
    LOGIN_PASSWORD_ERROR: 'You have entered invalid credentials.',
    PASSWORD_ERROR:
      'Password must be 8-16 chars, include uppercase, lowercase, numbers and special character',
    ENTER_OTP: 'Please enter OTP',
    ENTER_CONFIRM_PASSWORD: 'Please enter confirm password',
    ENTER_HANDLER: 'Please enter handler name',
    SELECT_COUNTRY_CODE: 'Please select country code',
    ENTER_PHONE: 'Please enter phone number',
    PASSWORD_NOT_MATCHED: 'Incorrect password',
    ENTER_VALID_PHONE: 'Please enter valid phone number',
    TERMS_CONDITION: 'Please accept terms and conditions',
    OTP_SENT: 'OTP has been sent',
    OTP_VERIFIED: 'OTP is verified',
    REGISTER_SUCCESS: 'You have registered successfully',
    OTP_WRONG: 'You have entered wrong OTP',
    LOGIN_SUCCESS: 'You have logged in successfully',
    NEW_PASSWORD: 'New password',
    CONFIRM_PASSWORD: 'Confirm new password',
    CANCELED_FACEBOOK_LOGIN: 'You have canceled facebook login',
    PASSWORD_RESET_SUCCESS: 'Password reset successfully',
    CANCELED_GOOGLE_LOGIN: 'You have canceled google login',
    REGISTRATION_REQUIRED: 'Please register your self first',
    SHARE_APPLE_EMAIL: 'Please share email id from apple',
    EMAIL_ADDRESS: 'Email address',
    EXIT_LIVE_STREAM: 'Are you sure you want to exit the live stream ?',
  },
  HOME: {
    SELECT_VIDEO_CATEGORY: 'Please select video category',
    COMMENT_ERROR: 'Please add comment',
    REPORT: 'Report',
    DELETE: 'Delete',
    ARCHIVED: 'archived',
    BLOCK: 'Block',
    REPORT_DISCARD: 'Are you sure you want to discard the changes?',
    BLOCK_MESSAGE: 'Are you sure you want to block the user?',
    DELETE_MESSAGE: 'Are you sure you want to delete the video?',
    REPORT_SUCCESS: 'Incident raised successfully',
    DELETE_SUCCESS: 'Video deleted successfully',
  },
  MARKET: {
    ORDER_PAYMENT_SUCCESS: 'Order Placed Successfully',
    PAYMENT_SUCCESS: 'Payment success',
    PAYMENT_CARD_ERROR: 'Your card number is incorrect',
    REMOVE_CART_PRODUCT:
      'Are you sure you want to remove the product from the cart?',
    EXIT_WRITE_REVIEW: 'Are you sure you want to exit ?',
  },
  PROFILE: {
    ENTER_USERNAME: 'Please enter username',
    USERNAME_SPACE_VALIDATION: 'Space is not allowed in username',
    ENTER_EMAIL: 'Please enter valid emai',
    ENTER_FIRST_NAME: 'Please enter first name',
    ENTER_LAST_NAME: 'Please enter last name',
    ENTER_COUNTRY_CODE: 'Please enter country code',
    ENTER_DESCRIPTION: 'Please enter description',
    ENTER_Mobile_NO: 'Please enter valid mobile number',
    BLOCK_USER: 'You have successfully blocked',
    UNBLOCK_USER: 'You have successfully unblocked',
    FAILED_TO_UNFOLLOW_USER: 'Failed to unfollow user',
  },
  COMMON: {
    PLEASE_TRY_AGAIN: 'Please try again',
    SOMETHING_WRONG: 'Something went wrong',
    LOGOUT: 'User logged out',
    ADDRESS_DELETED: 'Address deleted successfully',
    ACCOUNT_DELETED: 'Account deleted successfully',
    LOCATION_PERMISSION_DENIED: 'Location permission denied',
    LOCATION_PERMISSION_DENIED_PERMANENTLY:
      'Location permission denied permanently',
    PLEASE_ENABLE_IT_FROM_SETTING: 'Please enable it from settings',
    OPEN_SETTINGS: 'Open Settings',
    PLEASE_TURN_ON_LOCATION: 'Please turn on the location',
    TURN_ON: 'Turn on',
    ADDRESS_ADDED_SUCCESSFULLY: 'Address added successfully',
    ADDRESS_UPDATED_SUCCESSFULLY: 'Address updated successfully',
    UNABLE_TO_ADD_ADDRESS: 'Unable to add address',
    UNABLE_TO_UPDATE_ADDRESS: 'Unable to update address',
    INVALID_COUPON_CODE: 'Invalid Coupon Code!!',
    FAILED_TO_DELETE: 'Failed to delete',
    FAILED_TO_SEND: 'Failed to send',
    IMAGE_ERROR: 'You can send upto 15 images at a time.',
    IMAGE_SUCCESS: 'Your images upload soon it might takes some time.',
    ACCOUNT_IS_DELETED: 'Opps, This account is deleted',
  },
  UPLOAD: {
    SELECT_VIDEO: 'Please select video',
    ENTER_NAME: 'Please enter name',
    SELECT_CATEGORY: 'Please select categories',
    SELECT_STATUS_TYPE: 'Please select status type',
    SELECT_DESCRIPTION: 'Please select description',
    SUCCESS_VIDEO_UPLOAD:
      'Your video was uploaded successfully and is now processing. It will appear under your profile once the processing is complete.',
    ERROR_FILE_TYPE: 'Please upload MP4 or WebM video',
    ERROR_FILE_DURATION: 'Please upload video upto 30 minutes',
    UPLOAD_VIDEO_ERROR: 'Failed to upload the video. Please ',
    ERROR_TRY_AGAIN: 'try again!',
  },
  LIVE_ROOM: {
    EXIT_LIVE_STREAM: 'Are you sure you want to end the live stream ?',
  },
};

export const TITLES = {
  AUTH: {
    EMAIL_SIGNUP: 'Signup with Email',
    APPLE_SIGNUP: 'Signup with Apple',
    GOOGLE_SIGNUP: 'Signup with Google',
    FACEBOOK_SIGNUP: 'Signup with Facebook',
    INSTAGRAM_SIGNUP: 'Signup with Instagram',
    TO_CONTINUE: 'Signup to continue',
    ALREADY_ACC: 'Already have an account ? ',
    LETS_START: "Let's get started.",
    YOUR_HANDLE_NAME: "What's your handle name?",
    NEXT: 'Next',
    PLEASURE_TEXT: "It's a pleasure meeting you,",
    EMAIL_INSTRUCTION:
      'Kindly share email and mobile for better communication.',
    LAST_STEP: 'One last step...',
    PASSWORD_INSTRUCTION:
      'Please create and confirm your new password for security.',
    I_AGREE: 'I agree to',
    TERMS_AND_CONDITIONS: 'terms and conditions',
    PRIVACY_POLICY: 'privacy policy',
    HANDLE_NAME: 'Handle name',
    NEW_HERE: "I'm new here",
    HAVE_ACCOUNT: 'I have an account',
    SHOP_PRODUCT: 'Personalized Picks',
    SHOP_CAPTION: 'Dive into a world of trending videos and creative content',
    APPLE: 'Login with Apple',
    GOOGLE: 'Login with Google',
    FACEBOOK: 'Login with Facebook',
    INSTAGRAM: 'Login with Instagram',
    CONTINUE: 'Login to continue',
    FORGOT_PASSWORD: 'Forgot password',
    OR_LOGIN_WITH: 'Or login with',
    DONT_HAVE_AN_ACCOUNT: "Don't have an account",
    FORGOT_PASSWORD_DESCRIPTION:
      'Enter your email for the verification process, we will send 6 digits code to your email.',
    RESET_PASSWORD_DESCRIPTION:
      'Set the new password for your account so you login and access all the features.',
    ARE_YOU_SURE_YOU_WANT_TO_LOGOUT: 'Are you sure you want to Logout?',
    CONFIRM_PASSWORD: 'confirmNewPassword',
    NEW_PASSWORD: 'newPassword',
    FADE: 'fade',
    HEIGHT: 'height',
    UNDEFINED: 'undefined',
    OTP_TIME: 'otp_time',
    HANDLE_ERROR:
      "The handle name cannot contain the '@' symbol. Please choose a different handle.",
    RENDER_KEYS_AUTH: {
      CODE_FIELD: 'code_field',
      ONBOARDING_CAROUSEL: 'onboarding_carousel',
      CAROUSEL_ITEMS: 'carousel_items',
    },
  },
  COMMON: {
    SIGN_UP: 'Sign up',
    LOGIN: 'Login',
    BLOCK: 'Block',
    UNBLOCK: 'Unblock',
    BLOCKED: 'Blocked',
    ABOUT_APP: 'About App',
    ABOUT_VERSION: 'v',
    ADVERTISE_WITH_US: 'Advertise with us',
    EMAIL_ADDRESS: 'Email address',
    MOBILE_NUMBER: 'Mobile no',
    OPTIONAL_NUMBER: 'Mobile no (optional)',
    CONFIRM_PASSWORD: 'Confirm password',
    TAP_TO_REMOVE: 'Tap to remove',
    OTP_TITLE: 'Enter 6 digits code',
    OTP_SUB_TITLE: 'Enter the 6 digits code that you received on your',
    ABOUT_APP_TITLE: 'Current version of this app is',
    CONTINUE: 'Continue',
    PASSWORD: 'Password',
    RESET_PASSWORD: 'Reset password',
    CONFIRM_PASSWORD_2: 'confirmPassword',
    AND: ` & `,
    YES: 'Yes',
    NO: 'No',
    CANCEL: 'Cancel',
    DONE: 'done',
    CLOSE: 'Close',
    CREATE: 'create',
    START: 'start',
    FAST: 'fast',
    FUNCTION: 'function',
    NEXT: 'next',
    HALF: 'half',
    FULL: 'full',
    INTEREST: 'interest',
    COMMENT: 'comment',
    SEARCH: 'Search',
    FOLLOWERS: 'Followers',
    FOLLOW: 'Follow',
    FOLLOWING: 'Following',
    TIPS: 'Tips',
    LEARN_MORE: 'Learn More',
    LEARN_MORE_URL: 'https://trnd.is/events/?trend_id=',
    LEARN_MORE_TAVSID: '&tavsid=',
    LEARN_MORE_TAVUID: '&tavuid=',
    VIEW_ALL: 'View All',
    ADV: 'Adv',
    ADV_EYE_SIGN: 'i',
    VIEW_MORE: 'View More',
    VIEW_LESS: 'View Less',
    VIEW_CART: 'View Cart',
    ITEM: 'Item',
    WISHLIST: 'Wishlist',
    MOVE_TO_CART: 'Move to Cart',
    SUBMIT: 'Submit',
    OK: 'Ok',
    BLANK: '',
    HASH: '#',
    ATSIGN: '@',
    DOLLAR: '$',
    NO_DATA: 'No Data Found !',
    MINUS: '-',
    REMOVE: 'Remove',
    CONFIRM: 'Confirm',
    ADD: 'Add',
    SAVE: 'Save',
    PAGE_SIZE: 20,
    DELETE: 'Delete',
    DELETE_2: 'delete',
    USERNAME: 'Username',
    FIRST_NAME: 'First Name (optional)',
    DESCRIPTION: 'Description',
    LAST_NAME: 'Last Name (optional)',
    COUNTRY_CODE: 'Country code',
    CAMERA: 'Camera',
    GALLERY: 'Gallery',
    UNFOLLOW: 'Unfollow',
    LARGE: 'large',
    LOCATION: 'Please select your location',
    WHEN_IN_HOUSE: 'whenInUse',
    CREATE_2: 'create',
    SUBSCRIBE_2: 'subscribe',
    ERROR_MESSAGE: 'Something went wrong',
    BACK_WITHOUT_SAVE_MESSAGE:
      'Are you sure you want to exit without saving the details ?',
    PROFILE_SAVE_LOGOUT:
      "For security reasons, you'll need to log in again after updating your profile details.",
    BLOCK_CONFIRM: 'Are you sure you want to block',
    UNBLOCK_CONFIRM: 'Are you sure you want to un-block',
    NO_COMMENTS_YET: 'No Comments Yet',
    YOUR_CART_IS_EMPTY: 'Your Cart Is Empty!',
    YOUR_CART_IS_EMPTY_DESCRIPTION: `You have no items in your shopping cart. \n Let's go buy something`,
    CONTINUE_SHOPPING: 'Continue Shopping',
    DISCARD: 'Discard',
    COVER: 'cover',
    ZER0: '0 ',
    YOUR_WISHLIST_IS_PROD_EMPTY: 'Your wishlist product is currently empty.!',
    YOUR_WISHLIST_IS_PROD_EMPTY_DESCRIPTION: `You have no items in your wishlist. \n Start adding your favorite products to your wishlist.`,
    YOUR_WISHLIST_IS_VIDEO_EMPTY: 'Your wishlist video is currently empty.!',
    YOUR_WISHLIST_IS_VIDEO_EMPTY_DESCRIPTION: `You have no items in your wishlist. \n Start adding your favorite videos to your wishlist.`,
    APP_UPDATE_HEADER: 'Update available',
    UPDATE: 'Update',
    DEFAULT_PHONE_CODE: '',
    TOAST_SUCCESS_TYPE: 'success',
    TOAST_ERROR_TYPE: 'error',
    BUY_NOW: 'Buy Now',
    REELS_ACTION: {
      SAVE: 'save',
      LIKE: 'like',
      VOTE: 'vote',
      FOLLOW: 'follow',
      SHARE: 'share',
      COMMENT: 'comment',
    },
    VIDEO: 'video',
    PROFILE: 'profile',
    M3U8: 'm3u8',
    KEYBOARD_DID_SHOW: 'keyboardDidShow',
    KEYBOARD_DID_HIDE: 'keyboardDidHide',
    NUMBER_PAD: 'number-pad',
    ONE_TIME_CODE: 'oneTimeCode',
    COMMON_RENDER_KEYS: {
      DASHBOARD_MENU: 'dashboard_menu',
    },
    NO_INTERNET: {
      YOU_ARE_OFFLINE: 'No Internet Connection!',
      CHECK_YOUR_INTERNET: 'Please check your network connection',
      TRY_AGAIN: 'Try Again',
    },
    TEXTAREA: {
      BOTTOM: 'bottom',
      TOP: 'top',
      ERROR: 'error',
      DEFAULT: 'default',
    },
    COLON: ':',
    PIPE: '|',
    LENGTH_VALIDATION_1: 'must be',
    LENGTH_VALIDATION_2: 'characters or fewer.',
    TERMS:
      'By continuing and using our app you agree to our terms and condition, EULA, privacy policy, and all other policies found here.',
    REMIND_LATER: 'Remind me later',
    APP_UPDATE_TEXT:
      'To fully enjoy the latest features and enhancements, please update to the new version. If you choose not to update, you will miss out on exciting new features.',
    LOADING_TEXT: 'Loading...',
  },
  HOME: {
    NOT_INTERESTED: 'Not Interested',
    REPORT: 'Report',
    DELETE_VIDEO: 'Delete Video',
    LEARN_MORE: 'Learn more',
    LEARN_MORE_DESC:
      'Clicking this URL will navigate you away from the current screen. Please be aware that you will leave this page and be directed to a another page.',
    BLOCK_USER: 'Block User',
    SHARE_PROFILE: 'Share Profile',
    UNBLOCK_USER: 'UnBlock User',
    FOR_YOU: 'For You',
    FOLLOWING: 'Following',
    TRENDING: 'Trending',
    SELECT_TYPE: 'Select Type',
    SHARE_TITLE: 'Share via',
    SHARE_DESCRIPTION: 'Hey, check out this amazing video',
    COMMENTS: 'Comments',
    DESCRIBE_ISSUE: 'Describe the issue...',
    SEARCH: 'Search',
    CANCEL: 'Cancel',
    TOP: 'Top',
    ACCOUNTS: 'Accounts',
    VIDEOS: 'Videos',
    PRODUCTS: 'Products',
    HASHTAG: 'Hashtag',
    COMMENT: 'Comment',
    LIKE: 'Like',
    REPLY: 'Reply',
    DELETE: 'Delete',
    WRITE_A_COMMENT: 'Write a comment',
    NO_DATA_FOUND: 'No Data Found.',
    REPLIES: 'Replies',
    SUGGESTIONS: 'Suggestions',
    SAVE: 'save',
    LIVE: 'Live',
    GO_LIVE: 'Go Live',
    TIP_TITLE: 'Tip For :',
    SEND: 'Send',
    TOTAL_USERS: 'Total Users',
    TOTAL_EARN: 'Total Earn',
    PAY: 'Pay',
    DEMO_NAME: 'trendappend',
    ENTER_AMOUNT: 'Enter Amount',
    TIP_TYPE: ['10', '20', '30', 'Other'],
    TIP_KEY: 'tip_key',
    OTHER: 'Other',
    TIP_ERROR: 'Please enter the amount!',
    TIP_SELECT_ERROR: 'Please select the amount!',
    TIP_DESCRIPTION:
      'By continuing you agree to our terms and privacy polices and all other policies found here.',
    ADV_DESCRIPTION:
      "Discover The Simple Steps You're Missing That Will Dial In Your Sales And Follow-Up Process Causing Your Closing Ratio To Go Through The Roof",
    ADV_DESC_1: "I'm Not Your Typical Sales Guru...",
    ADV_DESC_2: "This Ain't Your Average Guidebook!",
    ADV_BUTTON: 'Download Free Copy Today!',
    FULL_NAME: 'Full Name',
    NAME: 'name',
    NUMBER: 'number',
    EMAIL_TITLE: 'Email Address',
    EMAIL: 'email',
    PHONE_CODE: 'phone_code',
    PHONE_ISO_CODE: 'phone_iso_code',
    PHONE_NUMBER: 'phone_number',
    COUNTRY_CODE: 'Country code',
    MOBILE_NUMBER: 'Mobile no',
    LEAD_SUCCESS_MESSAGE: 'Thank You',
    LEAD_ERROR_MESSAGE: 'Oops! We encountered an issue. Please try again!!',
    ALREADY_VOTED: 'Already voted.',
    VOTE_ADDED_SUCCESSFULLY: 'Vote added successfully.',
    LINK_COPIED: 'Link Copied!',
    WHATS_APP_ERROR_MSG:
      'WhatsApp is not installed. Please install it to proceed.',
    SUCCESS: 'Success',
    ERROR: 'Error',
    SHARE: 'Share',
    TAG_PEOPLE: 'Tag People',
    RENDER_KEYS: {
      VIDEO_ID: 'video_id',
      HOME_VIDEO_LIST: 'home_video_list',
      REPORT_REASON: 'report_reason_',
      REPORT_LIST: 'report_list',
      HOME_FILTER_RADIO: 'home_filter_radio',
      ACCOUNT_CARD_DATA: 'account_card_data',
      HASH_TAG_DATA: 'hash_tag_data',
      VIDEO_CARD_DATA: 'video_card_data',
      PRODUCT_CARD_DATA: 'product_card_data',
      HOME_TAB_DATA: 'home_tab_data',
      RENDER_MODAL_KEY: 'render_modal_key_',
      HOME_COMMENT: 'home_comment_',
      HOME_VIDEO_DETAIL: 'home_video_detail_',
    },
    GO_LIVE_MODAL: {
      NAME: 'Name',
      DESCRIPTION: 'Description',
      TITLE: 'Title',
      CAMPAIGN: 'Campaign',
      CAMPAIGN_TITLE: 'Campaign (optional)',
      SUBMIT: 'Submit',
      INVALID_FIELD: 'Please enter your ',
      MISSING_FIELDS: 'Fields are missing',
      SUCCESS_MSG: 'Details submitted successfully',
    },
  },
  MARKET: {
    HEADER_TAB_DATA: ['Products', 'Video'],
    PRODUCTS: 'Products',
    VIDEO: 'Video',
    ADD: 'Add',
    MOVE_TO_CART: 'Move to Cart',
    DELIVERY_TO_HOME: 'Delivery to Home',
    CHANGE: 'Change',
    PLEASE_SELECT_LOCATION: 'Please select location',
    TRENDING_PRODUCTS: 'Trending products',
    TRENDING_PRODUCT: 'Trending product',
    EXPLORE_MORE: 'Explore more',
    FILTER_BY_TEXT: 'Filter By',
    EXPLORE_MORE_SHOPPABLE_VIDEOS: 'Explore more shoppable videos',
    VIEW_MORE: 'View product',
    ADD_TO_WISH: 'Add in wishlist',
    REMOVE_TO_WISH: 'Remove in wishlist',
    HASHTAG: '#',
    BLANK_PLACEHOLDER: '-/-',
    BASED_ON_TEXT: 'Based on ',
    RATINGS: ' ratings',
    STAR: 'Star',
    COMMENT_HEADING: 'comment heading',
    MARKET_PROD_IMG_KEY_CARD: 'market_prod_img',
    MARKET_VIDEO_SHOP_KEY_CARD: 'market_video_shop_',
    MARKET_VIDEO_KEY_CARD: 'market_video_prod',
    MARKET_KEY_ORDER_CARD: 'market_my_order_',
    MARKET_KEY_CARD: 'market_prod_',
    EXPLORE_KEY_CARD: 'explore_more_prod',
    TRENDING_KEY_CARD: 'trending_product_',
    CUSTOMER: 'customer',
    MARKET_PLACE_PARAM: 'marketplace_top',
    TRENDING_HASHTAG: 'trending_hashtag',
    SHOPPABLE_VIDEO: 'shoppable_video',
    GET: 'get',
    WINDOW: 'window',
    DEFAULT_COUNTRY: 'US',
    SAVE: 'save',
    LIKE: 'like',
    VOTE: 'vote',
    FOLLOW: 'follow',
    SHARE: 'share',
    START: 'start',
    TEST: 'Test',
    VIDEO_TYPE: 'm3u8',
    CONTAIN: 'contain',
    COVER: 'cover',
    DATE_FORMAT: 'DD MMM YYYY',
    PRODUCT_DETAILS_LOCAL: 'product_details_local',
    PRODUCT_RATING: 'product_rating',
    COMMENT_LIST: 'comment_list',
    CAROUSEL_CARD_ITEM: 'carousel_card_item',
    CARD_LIST: 'card_list',
    ZER0: '0',
    VIDEO_CARD: 'video_card',
    PRODUCT_CARD: 'product_card',
    MARKET_HEADER_DATA: 'market_header_data',
    MARKET_BANNER_PAGINATION: 'market_banner_pagination',
    RENDER_TRENDING_PRODUCTS: 'render_trending_products',
    TODAY: 'Today',
    WISHLIST: {
      MOVE_ITEM_TO_CART: 'Successfully moved item to cart',
      NO_PRODUCT: 'No Products Found',
      NO_VIDEO: 'No Videos Found',
      MOVE_ITEM_TO_WISHLIST: 'Successfully moved item to wish list',
      REMOVE_ITEM_TO_WISHLIST: 'Successfully removed item from wish list',
    },
    FILTER_BY: {
      FILTER_SIDEBAR_DATA: ['Status', 'Price'],
      FILTER_BY_TEXT: 'Filter By',
      CLEAR_FILTER: 'Clear Filters',
      PRODUCT_FOUND: 'Product Found',
      APPLY: 'Apply',
      CATEGORY: 'Category',
      STATUS: 'Status',
      PRICE: 'Price',
      ALL: 'All',
      CATEGORY_CARD: 'category_card',
      FILTER_SIDEBAR: 'filter_sidebar',
      BOTTOM_TOOLTIP: require('../assets/pngs/bottomTooltip.png'),
    },
    CHANGE_LOCATION_WITH_SAVED_ADDRESS: {
      SEARCH_INPUT_PLACEHOLDER: 'Search',
      CANCEL: 'Cancel',
      USE_MY_CURRENT_LOCATION: 'Use my current location',
      ADD_NEW_ADDRESS: 'Add new address',
      SAVED_ADDRESS: 'Saved address',
      SAVED_ADDRESSES: 'Saved addresses',
      EDIT: 'Edit',
      DELETE: 'Delete',
      NO_ADDRESS_ADDED_YET: 'No address added yet',
      DELETE_MODAL_CONFIRMATION: 'Are you sure want to delete address ?',
      ADDRESS_LIST: 'addressList',
      SEARCH_ADDRESS: 'search_address',
      TAILS: 'tails',
    },
    SELECT_A_LOCATION: {
      SELECT_A_LOCATION_TEXT: 'Select a location',
      YOUR_LOCATION: 'Your Location',
      CHANGE: 'Change',
      CONFIRM_LOCATION: 'Confirm location',
      DUMMY_LOCATION:
        'Lotus Corporate Park,Off, Western Express Hwy, Geetanjali Railway Colony,',
      HOUSE_FLAT_BLOCK_NO: 'House / Flat / Block No',
      STRESS_ADDRESS: 'Street address',
      SHIPPING_FIRST_NAME: 'Shipping first name',
      SHIPPING_LAST_NAME: 'Shipping last name',
      SELECT_COUNTRY: 'Select country',
      LANDMARK: 'Landmark',
      STRESS_ADDRESS_2: 'Apartment,suite,unit,etc. (optional)',
      SAVE_AS: 'Save as',
      HOME: 'Home',
      OFFICE: 'Office',
      OTHER: 'Other',
      SAVE: 'Save',
      MOVE_MAP_TEXT: 'Move the map to see the location',
      ZIP_CODE: 'Zip code',
      STATE: 'State',
      CITY: 'City',
      EDIT_MODAL_CONFIRMATION:
        'Are you sure want to leave without edit address ?',
      GOOGLE: 'google',
      NUMERIC: 'numeric',
      SELECT_LOCATION: 'select_location',
      WHEN_IN_USE: 'whenInUse',
    },
    PRODUCT_DETAILS: {
      PRODUCT_DETAILS_TEXT: 'Product details',
      VIDEO_DETAILS_TEXT: 'Video details',
      FOLLOW: 'Follow',
      FOLLOWING: 'Following',
      WRITE_REVIEW: 'Write review',
      YOU_MIGHT_LIKE: {
        YOU_MIGHT_ALSO_LIKE: 'You might also like',
      },
      VERIFIED_PURCHASE: 'Verified Purchase',
      HELPFUL: 'Helpful',
      ADD_TO_CART: 'Add to cart',
    },
    WRITE_REVIEW: {
      WRITE_REVIEW_TEXT: 'Write review',
      RATE_THE_PRODUCT: 'Rate the product',
      TITLE: 'Title',
      WRITE_A_COMMENT: 'Write a Comment',
      REVIEW_SUCCESS_MESSAGE: 'Ratings added successfully.',
    },
    CREDIT_CARD: {
      CREDIT_CARD_TEXT: 'Credit Card',
      CARD_NUMBER: 'Card number',
      VALID_THROUGH: 'Valid through (MM/YY)',
      CVV: 'CVV',
      NAME_OF_CARD: 'Name on card',
      BILLING_POSTAL_CODE: 'Billing postal code',
      SAVE_MY_DETAILS_FUTURE_PAYMENT: 'Save my details for future payments',
      PAY_NOW: 'Pay now',
      ADD_NEW_CARD: 'Add new card',
      SAVED_ADDRESS: 'Saved cards',
      EXPIRE_DATE: 'Expiry Date :',
      UNKNOWN: 'Unknown',
      INVALID_CARD_NUMBER: 'Invalid card number',
      INVALID_CVV_NUMBER: 'Invalid CVV',
      INVALID_NAME_ON_CARD: 'Invalid name on card',
      INVALID_BILLING_POSTAL_CODE: 'Invalid billing postal code',
      INVALID_VALID_THROUGH: 'Invalid valid through',
      INVALID_EMAIL: 'Invalid email ID',
      NUMERIC: 'numeric',
      DECIMAL_PAD: 'decimal-pad',
      STRING: 'string',
      EXPLANATION_SIGN: '!',
    },
    YOUR_CART: {
      YOUR_CART_TEXT: 'Your cart',
      ITEMS: 'Items',
      ENTER_COUPON_CODE: 'Enter coupon code',
      APPLY: 'Apply',
      ORDER_SUMMARY: 'Order Summary',
      SUBTOTAL: 'Subtotal',
      SHIPPING_CHARGES: 'Shipping Charges',
      DISCOUNT_COUPON_CODE: 'Discount (Coupon Code)',
      TOTAL: 'TOTAL',
      YOU_WILL_SAVE: 'You will save',
      ON_THIS_ORDER: 'on this order',
      TOTAL_PRICE: 'Total Price',
      PLACE_ORDER: 'Place Order',
      FREE: 'Free',
      PLEASE_ENTER_COUPON_CODE: 'Please enter coupon code',
    },
    VIDEO_DETAILS: {
      AVAILABLE_PRODUCTS: 'Available Products',
    },
    MARKET_RENDER_KEYS: {
      PRODUCT_CART_DATA: 'product_cart_data',
      HEADER_TAB: 'header_tab',
      PRODUCT_CARD: 'product_card',
      VIDEO_CARD: 'video_card',
    },
    ORDER_DETAILS: {
      TITLE: 'Order Details',
      ORDER_SUMMARY: 'Order Summery',
      SUBTOTAL: 'Subtotal',
      SHIPPING_CHARGES: 'Shipping Charges',
      DISCOUNT: 'Discount',
      TOTAL: 'Total',
      SHIPPING_ADDRESS: 'Shipping Address',
      BILLING_ADDRESS: 'Billing Address',
      SHIPPING_METHOD: 'Shipping Method',
      PAYMENT_METHOD: 'Payment Method',
      SHIPPING_TIME: 'Shipping Time',
      RATE: 'Rate',
      MOBILE: 'Mobile',
      CANCEL_ORDER: 'Cancel Order',
      TRACK_ORDER: 'Track Order',
      RETURN_ORDER: 'Return Order',
      REORDER: 'Reorder',
      PENDING: 'Pending',
      DELIVERED: 'Delivered',
      SHIPPED: 'Shipped',
      CANCELED: 'Canceled',
      ORDERED: 'Ordered',
    },
    TRACK_ORDER: {
      TITLE: 'Track Order',
      PRODUCT_TITLE: 'Product Details',
      ORDER_DETAILS: 'Order Details',
      VIEW_BREAKUP: 'View Breakup',
      PRODUCT_TITLE_KEY: 'Product_Details',
      OTHER_PRODUCT_TITLE: 'Other items in this order',
      STATIC_TRACK_STEPS: [
        {
          name: 'Ordered',
          renderIcon: color => <ProductOrderedSvg color={color} />,
          description: 'Sat 03 May 2024',
        },
        {
          name: 'Shipped',
          renderIcon: color => <ProductShippedSvg color={color} />,
          description: '',
        },
        {
          name: 'Delivered',
          renderIcon: color => <ProductDeliveredSvg color={color} />,
          description: '',
        },
      ],
    },
  },
  MY_PROFILE: {
    BIO: 'Bio',
    PROFILE_DESC:
      'Quisque ornare auctor ex, rutrum condimentum orci porta non. Donec sed tincidunt diam, sit amet feugiat sapien.',
    EDIT_PROFILE: 'Edit Profile',
    PRIVACY_POLICY: 'Privacy And Policies',
    SEND_MESSAGE: 'Send Message',
    SHARE_PROFILE: 'Share Profile',
    PRODUCT: 'product',
    FOLLOWERS: 'followers',
    FOLLOWINGS: 'following',
    SAVE: 'save',
    TAG: 'tag',
    VOTE: 'vote',
    LIKE: 'like',
    VIDEO: 'video',
    FOLLOW: 'follow',
    SHARE: 'share',
    REMOVE_FOLLOWER: 'Remove follower',
    ARE_YOU_SURE: 'Are sure you wants to ',
    AVATAR_UPDATE_TOAST: 'Avatar Updated Successfully',
    FAILED_TO_SEND_MESSAGE: 'Failed to send message',
    PROFILE_UPDATE_SUCCESS_TOAST: 'Profile updated successfully',
    DELETE_ACCOUNT: 'Delete Account',
    DELETE_ACCOUNT_DESC: 'Are sure you want to delete account ?',
    LOGOUT: 'Logout',
    TOOLS: 'Tools',
    NO_VIDEO_FOUND: 'No Post Yet',
    NO_SAVE_ITEM: 'No Saved Items Yet',
    NO_TAG_ITEM: 'No Tagged Items Yet',
    NO_PRODUCT_FOUND: 'No Products for Sale yet',
    VIEW: 'view',
    UNBLOCK_USER: 'Unblock User',
    BLOCK_USER: 'Block User',
    DESCRIPTION: 'Description (optional)',
    EDIT_PROFILE_FIELDS: {
      UPDATE_HANDLE: 'update_handle',
      UPDATE_EMAIL: 'update_email',
      FIRST_NAME: 'first_name',
      LAST_NAME: 'last_name',
      PHONE_CODE: 'phone_code',
      PHONE_ISO_CODE: 'phone_iso_code',
      PHONE_NUMBER: 'phone_number',
      DESCRIPTION: 'description',
    },
    MY_PROFILE_RENDER_KEYS: {
      PROFILE_ICON_DATA: 'profile_icon_data',
      PROFILE_TAB_DATA: 'profile_tab_data',
    },
    SHOP_SETTING: {
      TITLE: 'Shop Setting',
      SAVE: 'Save',
      COMPANY: 'Company',
      ADDRESS: 'Address',
      CITY: 'City',
      REGION: 'Region',
      ZIP: 'Zip',
      COUNTRY: 'Country',
      EMAIL: 'email',
      NUMBER: 'number',
      PHONE_CODE: 'phone_code',
      MOBILE_NUMBER_KEY: 'mobile number',
      CUSTOMER_EMAIL: 'Customer Email',
      MOBILE_NUMBER: 'Mobile no',
      MAIN_WEBSITE_URL: 'Main Website URL',
      FACEBOOK: 'Facebook',
      INSTAGRAM: 'Instagram',
      TWITTER: 'Twitter',
      YOUTUBE: 'Youtube',
      STORE_PRIVACY_URL: 'Store Privacy URL',
      STORE_TERMS_URL: 'Store Terms URL',
      INVALID_FIELD: 'Please enter your',
      INVALID_EMAIL: 'Please enter your valid email',
      INVALID_NUMBER: 'Please enter your valid mobile number',
      INVALID_NAME: 'Please enter your valid full name.',
      INVALID_URL: 'Please enter your valid URL',
      INVALID_ZIP_CODE: 'Please enter your valid zip',
      MISSING_FIELDS: 'Fields are missing',
      INVALID_FIELDS: 'Fields are invalid',
      URL_FIELD: [
        'terms',
        'privacy',
        'instagram',
        'twitter',
        'youtube',
        'facebook',
        'url',
      ],
      INVALID_ID_FIELD: ['instagram', 'twitter', 'youtube', 'facebook'],
      UPDATE_SUCCESS: 'Shop setting updated successfully',
      COUNTRY_CODE: 'Country code',
      NUMBER_PAD_TYPE: 'number-pad',
      ERROR: 'error',
      DEFAULT_PHONE_CODE: '',
      PADDING: 'padding',
      HEIGHT: 'height',
      POSITION: 'position',
      SHOP_SETTING_FIELD: {
        COMPANY: 'company',
        ADDRESS: 'address',
        CITY: 'city',
        REGION: 'region',
        ZIP: 'zip',
        EMAIL: 'email',
        PHONE_CODE: 'phone_code',
        PHONE_ISO_CODE: 'phone_iso_code',
        NUMBER: 'number',
        COUNTRY: 'country',
        URL: 'url',
        FACEBOOK: 'facebook',
        INSTAGRAM: 'instagram',
        TWITTER: 'twitter',
        YOUTUBE: 'youtube',
        PRIVACY: 'privacy',
        TERMS: 'terms',
      },
    },
  },
  UPLOAD: {
    UPLOAD_VIDEO: 'Upload Video',
    POST_VIDEO: 'Post Video',
    NAME: 'Name',
    TAG: 'Tag',
    TAG_PEOPLE: 'Tag People',
    DESCRIPTION: 'Description',
    POST: 'Post',
    SAVE_DRAFT: 'Save Draft',
    STATUS_TYPE: 'Status Type',
    PUBLIC: 'Public',
    PRIVATE: 'Private',
    CATEGORIES: 'Categories',
    BOTTOM: 'bottom',
    CONTINUE_EDITS: 'Continue edits',
    BUY_NOW: 'Buy Now',
    DELETE_VIDEO_MESSAGE: 'Remove this video?',
    DISCARD_VIDEO_MESSAGE:
      'Discard this post? the video and all edits will be discarded',
    VIDEO_DESCRIPTION: `Long videos can be split into multiple parts \n to get more exposure`,
    VIDEO_SIZE_DESCRIPTION: `720x1280 resolution or higher\n Up to 30 minutes Less than 2 GB`,
    END_STREAM: 'endStream',
    UPLOAD_FIELD: {
      PUBLIC: 'public',
      PRIVATE: 'private',
      DRAFT: 'draft',
      VIDEO_TYPE: 'video_type',
      DESCRIPTION: 'description',
      CATEGORY: 'category',
      VIDEO_NAME: 'video_name',
      TAG_NAME: 'tag_name',
      URI: 'uri',
      OPTIONAL_KEYS: ['video_name', 'description', 'video_type'],
    },
    VIDEO_STATUS: {
      PUBLIC: 'public',
      PUBLISHED: 'published',
    },
    CAT_DATA: [
      { label: 'video', value: 'video' },
      { label: 'video2', value: 'video2' },
    ],
    SOCKET_ACTION: {
      ADD_MEMBER: 'add_member',
      CREATE_MESSAGE: 'create_message',
      RECIEVE_MESSAGE: 'receive_message',
      MESSAGE_LIST: 'message_list',
      UPDATED_INVENTORY: 'updated_inventory',
      PUSH_MESSAGE: 'push_message',
    },
    NEXT: 'Next',
  },
  NOTIFICATION: {
    NOTIFICATION_TAB_DATA: ['Messages', 'Notifications'],
    NOTIFICATION_TAGS: [
      'voted',
      'liked',
      'new_video',
      'share_video',
      'shared',
      'video_tag',
    ],
    NOTIFICATION_COMMENTS: [
      'comment_like',
      'comment',
      'comment_tag',
      'comment_reply',
    ],
    MESSAGES: 'Messages',
    NOTIFICATIONS: 'Notifications',
    NO_MESSAGE: 'Your Inbox Is Empty!',
    TYPE_MESSAGE: 'Type a message',
    MESSAGE_LIST: 'message_list',
    NOTIFICATION_TAB: 'notification_tab_data',
    DELETE: 'Delete',
    ORDERED: 'Ordered',
    READ_STATUS: 'read_status',
    READ: 'read',
    NOT_READ: 'notread',
    AM: 'AM',
    PM: 'PM',
    YOU_HAVE_NO_CONVERSATION: "You have no conversations. Let's get chatting!",
    VOTED: 'voted',
    LIKED: 'liked',
    NEW_VIDEO: 'new_video',
    SHARE_VIDEO: 'share_video',
    SHARED: 'shared',
    FOLLOWED: 'followed',
    SHARED_PROFILE: 'share_profile',
    COMMENT_LIKE: 'comment_like',
    COMMENT_TAG: 'comment_tag',
    COMMENT_REPLY: 'comment_reply',
    LIVE: 'live',
    COMMENT: 'comment',
    ROOM_DELETE: 'Are you sure you want to delete chat ?',
    POP_UP_NAME: 'ProfileFollowers',
    MESSAGE: 'message',
    VIEW_PROFILE: 'View Profile',
  },
  LIVE_ROOM: {
    WRITE_COMMENT: 'Write a comment',
    STREAM_END_TEXT: 'Live Stream Has Ended !!',
    LIVE_STREAM_SUCCESS_MESSAGE: 'Details submitted successfully',
  },
};

export const STATIC_VALUES = {
  AUTH: {
    OTP_CELL_COUNT: 6,
    ON_BOARDING: [
      {
        id: 0,
        title: 'Personalized Picks',
        subtitle: 'Dive into a world of trending videos and creative content.',
        uri: require('../assets/pngs/on-boarding-1.png'),
      },
      {
        id: 1,
        title: 'Marketplace',
        subtitle: 'Elevate your shopping experience with our marketplace.',
        uri: require('../assets/pngs/on-boarding-2.png'),
      },
      {
        id: 2,
        title: 'Profile Management',
        subtitle: 'Your personalized hub for managing content and settings.',
        uri: require('../assets/pngs/on-boarding-3.png'),
      },
    ],
  },
  COMMON: {
    APP_PLAYSTORE_URL:
      'https://play.google.com/store/apps/details?id=com.trendappend',
    APP_APPSTORE_URL: 'https://apps.apple.com/in/app/trend-append/id6511224298',
    IMAGE_THUMBNAIL: require('../assets/pngs/placeholder-image.png'),
    DOT_IMAGE: require('../assets/pngs/dot.png'),
    NOTIFICATION_THUMBNAIL: 'https://users.trend.app/u/4378/1000127326.jpg.jpg',
    VIDEO_URL_SUFFIX: '/manifest.m3u8',
    IMAGE_URL_SUFFIX: '/thumbnail_0.jpg',
    TERMS_AND_CONDITION_LINK: 'https://trend.app/policies/privacy',
    OTP_TIME: 900,
    URL_REGEX: /(https?:\/\/[^\s/$.?#].[^\s]*)/gi,
    EMOJI_REGEX: [
      '(?:[\u2700-\u27bf]|(?:\ud83c[\udde6-\uddff]){2}|[\ud800-\udbff][\udc00-\udfff]|[\u0023-\u0039]\ufe0f?\u20e3|\u3299|\u3297|\u303d|\u3030|\u24c2|\ud83c[\udd70-\udd71]|\ud83c[\udd7e-\udd7f]|\ud83c\udd8e|\ud83c[\udd91-\udd9a]|\ud83c[\udde6-\uddff]|[\ud83c[\ude01-\ude02]|\ud83c\ude1a|\ud83c\ude2f|[\ud83c[\ude32-\ude3a]|[\ud83c[\ude50-\ude51]|\u203c|\u2049|[\u25aa-\u25ab]|\u25b6|\u25c0|[\u25fb-\u25fe]|\u00a9|\u00ae|\u2122|\u2139|\ud83c\udc04|[\u2600-\u26FF]|\u2b05|\u2b06|\u2b07|\u2b1b|\u2b1c|\u2b50|\u2b55|\u231a|\u231b|\u2328|\u23cf|[\u23e9-\u23f3]|[\u23f8-\u23fa]|\ud83c\udccf|\u2934|\u2935|[\u2190-\u21ff])',
    ],
    GOOGLE_APP_REVIEW: {
      INSTALL_TIME: 'installTime',
      REVIEW_INTERVAL_TIME: 30,
      REVIEW_INTERVAL_DELAY: 10 * 60 * 1000,
    },
    APP_UPDATE_ALERT: {
      INSTALL_TIME: 'appUpdateInitialTime',
    },
    MODAL_TYPE: {
      OTP_MODAL: 'Otp',
      REGISTER: 'register',
      EMAIL_MODAL: 'email',
      FORGOT_PASSWORD_MODAL: 'forgotPassword',
    },
    TOASTER_TYPE: {
      SUCCESS: 'success',
      BOTTOM: 'bottom',
      ERROR: 'error',
      DEFAULT_TIME: 1500,
    },
    SOCIAL_AUTH: {
      FACEBOOK: 'facebook',
      APPLE: 'apple',
      GOOGLE: 'google',
      INSTAGRAM: 'instagram',
    },
    STATUS_CODES: {
      SUCCESS: 200,
      SESSION_EXPIRE: '801',
      SUCCESS_SECONDARY: 100,
      UNAUTHORISED: '667',
    },
    PLATFORM: {
      ANDROID: 'android',
      IOS: 'ios',
    },
    DEEP_LINKING: {
      prefixes: 'https://trend.app/',
      PREFIX_HOST: 'trend.app',
      PROTEACTED_ROUTES: ['policies/privacy'],
      config: {
        screens: {
          Main: '/',
          Login: '/auth/login',
          Registration: 'auth/signup',
          ProfilePublic: '/profile/:username',
          StreamList: '/live-streaming',
          YourCart: '/cart',
          Location: '/profile/my-addresses',
          Wishlist: '/profile/my-wishlist',
          MyOrders: '/profile/my-orders',
          ShopSetting: '/profile/shop-setting',
          ProductDetails: '/market/product/:id',
          VideoDetails: '/market/video/:id',
          ProfileVideoDetail: '/video/:id',
          PrivacyPolicy: 'policies/privacy',
          TermsAndConditions: 'policies/terms',
        },
      },
      authRoutes: [
        'Login',
        'Registration',
        'PrivacyPolicy',
        'TermsAndConditions',
      ],
      authPaths: [
        'auth/login',
        'auth/signup',
        'policies/privacy',
        'policies/terms',
      ],
      routes: [
        { name: 'Login', path: '/auth/login' },
        { name: 'Registration', path: '/auth/signup' },
        { name: 'ProfilePublic', path: '/profile/:username' },
        { name: 'StreamList', path: '/live-streaming' },
        { name: 'YourCart', path: '/cart' },
        { name: 'Location', path: '/profile/my-addresses' },
        { name: 'Wishlist', path: '/profile/my-wishlist' },
        { name: 'MyOrders', path: '/profile/my-orders' },
        { name: 'ShopSetting', path: '/profile/shop-setting' },
        { name: 'ProductDetails', path: '/market/product/:id' },
        { name: 'ProductDetails', path: '/market/video/:id' },
        { name: 'ProfileVideoDetail', path: '/video/:id' },
        { name: 'PrivacyPolicy', path: '/policies/privacy' },
        { name: 'TermsAndConditions', path: '/policies/terms' },
      ],
      policyRoutes: [
        { name: 'PrivacyPolicy', path: '/policies/privacy' },
        { name: 'TermsAndConditions', path: '/policies/terms' },
      ],
    },
    WEB_CLIENT_ID:
      '928922921289-7d0a95c2d61bn4468g8gdvtja0gl8hic.apps.googleusercontent.com',
    INSTAGRAM_CLIENT_ID: '1032485284892893',
    INSTAGRAM_KEY: '82905188c2bab64001d1b47151c354eb',
    INSTAGRAM_REDIRECT_URL: 'https://trend.app/',
    SNAP_TO_INTERVAL_HEIGHT:
      Platform.OS === 'android'
        ? Dimensions.get('window').height - moderateScale(75)
        : Dimensions.get('window').height - moderateScale(80),
    KEYS: {
      TREND_API_TOKEN: 'trend_api_token',
      USER_DATA: 'user_data',
      IS_PROTECTED: 'is_protected',
      USER_ACCESS_TOKEN: 'access_token',
      LOGGED_IN_PROFILE: 'loggedInProfile',
      TAVSID: 'tavsid',
      FCM_TOKEN: 'fcmToken',
      LOCAL_CART_DATA: 'localCartData',
      CURRENT_SELECTED_ADDRESS: 'currentSelectedAddress',
      COUNTRY_CODE: 'country_code',
    },
    SCREEN_DIMENSIONS: {
      SCREEN_HEIGHT: Dimensions.get('window').height,
      SCREEN_WIDTH: Dimensions.get('window').width,
    },
    SCREEN: {
      SPLASH: 'Splash',
      ONBOARDING: 'OnBoarding',
      REGISTRATION: 'Registration',
      LOGIN: 'Login',
      CONGRATULATION: 'Congratulation',
      MAIN: 'Main',
      HOME: 'Home',
      SUGGESTED_ACCOUNT: 'Suggested Account',
      TERMS_AND_CONDITION: 'TermsAndConditions',
      PRIVACY_POLICY: 'PrivacyPolicy',
      MARKET: 'Market',
      MARKET_MAIN: 'Market_MAIN',
      SHOPPABLE_VIDEOS: 'SHOPPABLE_VIDEOS',
      LOCATION: 'Location',
      SELECT_LOCATION: 'SelectLocation',
      WISHLIST: 'Wishlist',
      FILTER_BY: 'FilterBy',
      PRODUCT_DETAILS: 'ProductDetails',
      COMMENTS: 'Comments',
      SEARCH_HOME: 'SearchHome',
      VIDEO_DETAIL: 'VideoDetails',
      HOME_VIDEO: 'HomeVideo',
      WRITE_REVIEW: 'WriteReview',
      PROFILE_MENU: 'ProfileMenu',
      PROFILE_PUBLIC: 'ProfilePublic',
      PROFILE_VIDEO_DETAIL: 'ProfileVideoDetail',
      CREDIT_CARD: 'CreditCard',
      YOUR_CART: 'YourCart',
      PROFILE: 'Profile',
      PROFILE_FOLLOWERS: 'ProfileFollowers',
      PROFILE_FOLLOWINGS: 'ProfileFollowings',
      BLOCKER_USERS: 'BlockedUsers',
      ABOUT_APP: 'AboutApp',
      EDIT_PROFILE: 'EditProfile',
      ADVERTISE_WITH_US: 'AdvertiseWithUS',
      VIEW_MORE_PRODUCTS: 'ViewMoreProducts',
      SHOP_SETTING: 'ShopSetting',
      MY_ORDERS: 'MyOrders',
      ORDER_DETAILS: 'OrderDetails',
      VIDEO_PRODUCTS: 'VideoProducts',
      SEARCH_MARKET_PLACE: 'searchMarketPlace',
      UPLOAD: 'upload',
      NOTIFICATION: 'Notifications',
      TRACK_ORDER: 'TrackOrder',
      MESSAGES: 'Messages',
      MESSAGE_MEDIATOR: 'MessageMediator',
      LIVE_STREAM_ROOM: 'LiveStreamRoom',
      STREAM_LIST: 'StreamList',
      VIDEO_EDITOR: 'VideoEditor',
      VIDEO_UPLOAD: 'VideoUpload',
      VIDEO_DETAILS: 'VideoDetails',
      SHARE: 'Share',
      TAG_PEOPLE: 'TagPeople',
    },
    FONT_FAMILY: {
      ROBOTO_BLACK: 'Roboto-Black',
      ROBOTO_REGULAR: 'Roboto-Regular',
      ROBOTO_MEDIUM: 'Roboto-Medium',
      ROBOTO_BOLD: 'Roboto-Bold',
      ALMARAI_REGULAR: 'Almarai-Regular',
      ALMARAI_BOLD: 'Almarai-Bold',
    },
    DARK_THEME_COLORS: {
      BLACK: '#121212',
      BLACK_2: '#141414',
      WHITE: '#FFFFFF',
      BLUE: '#188BFF',
      LIGHT_BLUE: '#76BAFF',
      DARK_BLUE: '#233241',
      GREY: '#B6BDCB',
      GREY_2: '#3C3B3B',
      GREY_3: '#666666',
      GREY_4: '#707070',
      DARK_GREY: '#A6A6A6',
      PLACEHOLDER_BLACK: '#2D2D2F',
      INPUT_BACKGROUND_BLACK: '#1F1F1F',
      INPUT_BACKGROUND_BLACK_2: '#292929',
      INPUT_BACKGROUND_BLACK_3: '#3C3B3B',
      LIGHT_GREY: '#A7A7A7',
      RED: '#C31514',
      RED_2: '#FF0000',
      RED_3: '#FF0E0E',
      GREEN: '#34A043',
      DARK_GREEN: '#026440',
      LIGHT_GREEN: '#5EFF74',
      LIGHT_GREEN_2: '#34A043',
      DARK_GREY_2: '#3C3C3C68',
      LIGHT_BLACK: '#383737bd',
      ORANGE: '#FF7B30',
      YELLOW: '#FFDC00',
    },
    LIGHT_THEME_COLORS: {
      BLACK: '#121212',
      BLACK_2: '#141414',
      WHITE: '#FFFFFF',
      BLUE: '#188BFF',
      LIGHT_BLUE: '#76BAFF',
      GREY: '#B6BDCB',
      GREY_2: '#3C3B3B',
      GREY_3: '#666666',
      GREY_4: '#707070',
      DARK_GREY: '#A6A6A6',
      DARK_GREY_3: '#8B8B8B',
      PLACEHOLDER_BLACK: '#2D2D2F',
      INPUT_BACKGROUND_BLACK: '#1F1F1F',
      INPUT_BACKGROUND_BLACK_2: '#292929',
      INPUT_BACKGROUND_BLACK_3: '#3C3B3B',
      LIGHT_GREY: '#A7A7A7',
      RED: '#C31514',
      RED_2: '#FF0000',
      GREEN: '#34A043',
      DARK_GREEN: '#026440',
      LIGHT_GREEN: '#5EFF74',
      DARK_GREY_2: '#3C3C3C68',
      LIGHT_BLACK: '#383737bd',
      ORANGE: '#FF7B30',
      YELLOW: '#FFDC00',
      RED_3: '#FF5252',
    },
    PAYMENT_TYPE: {
      LIVE_TIP: 'LIVE_TIP',
      TIP: 'TIP',
    },
    SUPPORTED_VIDEO_TYPES: ['hevc', 'HEVC'],
    FILE_TYPE: {
      VIDEO: 'video',
      PHOTO: 'photo',
    },
    DISPLAY_MODES: {
      DARK_MODE: 'dark_mode',
      LIGHT_MODE: 'light_mode',
    },
    CURRENT_MODE: 'dark_mode',
    GRADIENT_COLOR: ['#000000', '#191919C0', '#3C3C3C68', '#FFFFFF00'],
    GRADIENT_COLOR_1: ['#000000', '#00000033', '#00000000'],
    ERROR_CODE: {
      499: '499',
    },
    DONATION_KEYS: {
      LIVE_ID: 'live_id',
      TREND_ID: 'trend_id',
    },
  },
  MARKET: {
    FILTER_BY_DATA: {
      CATEGORY_DATA: [
        { title: 'All', checked: false },
        { title: 'Category 01', checked: false },
        { title: 'Category 02', checked: false },
        { title: 'Category 03', checked: false },
        { title: 'Category 04', checked: false },
        { title: 'Category 05', checked: false },
      ],
      STATUS_DATA: [
        { title: 'All', checked: false },
        { title: 'Pending', checked: false },
        { title: 'Shipped', checked: false },
        { title: 'Delivered', checked: false },
        { title: 'Canceled', checked: false },
      ],
    },
    SELECT_A_LOCATION_DATA: {
      HOME_OFFICE_OTHER: ['Home', 'Office', 'Other'],
    },
    PRODUCT_DETAILS_DATA: {
      PRODUCT_DATA: {
        descriptionText: 'Description',
        sellerDetails: {
          sellerDetailsText: 'Seller details',
        },
      },
      CUSTOMER_REVIEW: {
        customReviewText: 'Customer review',
        outOf: 'out of 5',
      },
    },
    CREDIT_CARD_CONSTANTS: {
      CARD_NUMBER: 'cardNumber',
      CVV: 'cvv',
      NAME_OF_CARD: 'nameOfCard',
      BILLING_POSTAL_CODE: 'billingPostalCode',
      VALID_THROUGH: 'validThrough',
      TREND_EMAIL: 'trend_email',
      VISA: 'Visa',
      MASTERCARD: 'Master Card',
      AMEX: 'amex',
      AMERICAN_EXPRESS: 'American Express',
      DISCOVER: 'discover',
      UNKNOWN: 'Unknown',
      YES: 'yes',
      NO: 'no',
      DUMMY_CARD_NUMBER: '**** **** ***** ',
      DOLLAR: ' $ ',
      CART: 'cart',
      DONATION: 'donation',
      TIP: 'tip',
      TIP_LIVE: 'tip_live',
      INVALID_CODE: '000000',
    },
    MY_ORDER_CONSTANTS: {
      PENDING: 'Pending',
      DELIVERED: 'Delivered',
      CANCELED: 'Canceled',
      ORDERED: 'Ordered',
      SHIPPED: 'Shipped',
      MY_ORDERS: 'My Orders',
      FILTER: 'Filter',
      SEARCH_ORDERS: 'Search orders',
      ORDERED_KEY: 'order',
      RATE: 'Rate',
    },
    SELECT_LOCATION_CONSTANT: {
      LOCATION_PERMISSION: 'Location Permission',
      LOCATION_MESSAGE:
        'We need access to your location to provide better service.',
      ASK_ME_LATER: 'Ask Me Later',
      OK: 'Ok',
      POSTAL_CODE: 'postal_code',
      ADMINISTRATIVE_AREA_LEVEL_1: 'administrative_area_level_1',
      LOCALITY: 'locality',
      ADMINISTRATIVE_AREA_LEVEL_2: 'administrative_area_level_2',
      SUBLOCALITY: 'sublocality',
      COUNTRY: 'country',
      ROUTE: 'route',
      PLUS_CODE: 'plus_code',
      STREET_ADDRESS: 'street_address',
      NEIGHBORHOOD: 'neighborhood',
      INTERSECTION: 'intersection',
      PREMISE: 'premise',
      STREET_NUMBER: 'street_number',
      SUB_LOCALITY: 'sublocality',
      SUB_LOCALITY_LEVEL_1: 'sublocality_level_1',
      SUB_LOCALITY_LEVEL_2: 'sublocality_level_2',
      COUNTRY_TITLE: 'Country',
      OTHER: 'Other',
      FIRST_NAME: 'firstName',
      LAST_NAME: 'lastName',
      STREET_ADDRESS: 'streetAddress',
      STREET_ADDRESS_2: 'streetAddress2',
      HOUSE_NO: 'houseNo',
      LANDMARK: 'landMark',
      HOME: 'Home',
      OFFICE: 'Office',
      MAP_KEY_LABEL: '&key=',
      MAP_KEY: 'AIzaSyAuBSb8wTr_t6M6_YUcDgcjCtQGdQHr-l0',
      CITY: 'city',
      STATE: 'state',
      ZIP_CODE: 'zipCode',
      ERROR_MSG: {
        SHIPPING_FIRST_NAME: 'Please enter valid shipping first name',
        SHIPPING_LAST_NAME: 'Please enter valid shipping last name',
        CITY: 'Please enter valid city name',
        STATE: 'Please enter valid state name',
        STREET_ADDRESS: 'Please enter valid shipping street address',
        OTHER_INPUT: 'Please enter other name',
        ZIP_CODE: 'Please enter valid zip code',
      },
    },
    VIDEO_PRODUCTS_DATA: {
      TITLE: 'There has never been a better time to start a faceless youtube',
    },
    ORDER_DETAILS_DATA: {
      order_date: '03 May 2024',
      status: 'Delivered',
      order_rate: 3.5,
      shipping_method: 'Via',
      payement_method: 'Credit Card **** **** **** ',
      shipping_time: '11:00 AM - 12:30 PM (27 Nov)',
    },
  },
  HOME: {
    REPORTS_REASON_LIST: [
      {
        id: 0,
        label: 'Physical violence and violent threats',
      },
      {
        id: 1,
        label: 'Exploitation and abuse of people under 18',
      },
      {
        id: 2,
        label: 'Other Describe the issue...',
      },
    ],
    TOP_RESULTS_SECTIONS: {
      PEOPLE: 'people',
      PRODUCTS: 'products',
      VIDEOS: 'videos',
    },
    HOME_COMMENT_TAIL: 'tail',
    HOME_REPLIES: 'replies',
    HOME_LIKE: 'like',
    HOME_DISLIKE: 'dislike',
    HOME_DATA: {
      TAB_DATA: ['Top', 'Accounts', 'Videos', 'Products'],
    },
    GET_IP_STATIC_ENDPOINT: 'https://api.ipify.org?format=json',
    SOCIAL_SHARE_DATA: [
      {
        id: 1,
        name: 'Facebook',
        imgSrc: <FacebookSvgIcon />,
      },
      {
        id: 2,
        name: 'Twitter',
        imgSrc: <TwitterSvgIcon />,
      },
      {
        id: 3,
        name: 'Linkedin',
        imgSrc: <LinkedinSvgIcon />,
      },
      {
        id: 4,
        name: 'Whatsapp',
        imgSrc: <WhatsappSvgIcon />,
      },
      {
        id: 5,
        name: 'Link',
        imgSrc: <CopyLinkSvgIcon />,
      },
    ],
  },
  NOTIFICATION: {
    FILE: 'File',
    SOCKET_KEYS: {
      MESSAGE_LIST: 'message_list',
      CREATE_MESSAGE: 'create_message',
      ADD_REACTION: 'add_reaction',
      REMOVE_REACTION: 'remove_reaction',
      SEND_IMAGE: 'send_image',
      ROOM_LIST: 'room_list',
      DELETE_ROOM: 'delete_room',
      READ_MESSAGE: 'message_read',
      RECEIVE_MESSAGE: 'receive_message',
      CREATE_ROOM: 'create_room',
      UPDATED_ROOM_LIST: 'updated_room_list',
      READ_LIST: 'read_list',
      UPDATED_READ: 'updated_read',
      UPDATED_ROOM_READ: 'updated_room_read',
      PROFILE_ICON_DATA: 'profile_icon_data',
      VIEW: 'view',
    },
    PROFILE_DATA: [
      {
        id: 1,
        icon: <OverViewIcon color={getColors().WHITE} />,
        label: '0',
        name: 'view',
        key: 'traffic',
        type: 'view',
      },
      {
        id: 2,
        icon: <FollowersIcon color={getColors().WHITE} />,
        label: '0',
        name: 'followers',
        key: 'followers',
        type: 'action',
      },
      {
        id: 3,
        icon: <FollowingIcon color={getColors().WHITE} />,
        label: '0',
        name: 'following',
        key: 'following',
        type: 'action',
      },
    ],
  },
  PROFILE: {
    PROFILE_MENU_LIST: [
      {
        name: 'Shop Setting',
        screenRoute: 'ShopSetting',
      },
      {
        name: 'My Orders',
        screenRoute: 'MyOrders',
      },
      {
        name: 'My Wishlist',
        screenRoute: 'Wishlist',
      },
      {
        name: 'My Addresses',
        screenRoute: 'Location',
      },
      {
        name: 'About App',
        screenRoute: 'AboutApp',
      },
      {
        name: 'Blocked',
        screenRoute: 'BlockedUsers',
      },
      {
        name: 'Tools',
        screenRoute: '',
      },
      {
        name: 'Privacy And Policies',
        screenRoute: 'PrivacyPolicy',
      },
    ],
    PROFILE_DATA: {
      ICON_DATA: [
        {
          id: 1,
          icon: <OverViewIcon />,
          label: '0',
          name: 'view',
          key: 'traffic',
          type: 'view',
        },
        {
          id: 2,
          icon: (
            <WishlistIcon
              height={21}
              width={21}
              color={getColors().LIGHT_GREY}
            />
          ),
          label: '0',
          name: 'likes',
          key: 'likes',
          type: 'view',
        },
        {
          id: 3,
          icon: <FollowersIcon />,
          label: '0',
          name: 'followers',
          key: 'followers',
          type: 'action',
        },
        {
          id: 4,
          icon: <FollowingIcon />,
          label: '0',
          name: 'following',
          key: 'following',
          type: 'action',
        },
      ],
      TAB_DATA: [
        {
          icon: <PlayProfileIcon color={getColors().LIGHT_GREY} />,
          activeIcon: <PlayProfileIcon color={getColors().BLUE} />,
          name: 'video',
        },
        {
          icon: <BookmarkIconProfile color={getColors().LIGHT_GREY} />,
          activeIcon: <BookmarkIconProfile color={getColors().BLUE} />,
          name: 'save',
        },
        {
          icon: <TagListSvgIcon color={getColors().LIGHT_GREY} />,
          activeIcon: <TagListSvgIcon color={getColors().BLUE} />,
          name: 'tag',
        },
        {
          icon: <ShopProfileIcon color={getColors().LIGHT_GREY} />,
          activeIcon: <ShopProfileIcon color={getColors().BLUE} />,
          name: 'product',
        },
      ],
    },
  },
  UPLOAD: {
    LIVE_KIT_WS_URL: 'wss://trendapp-caj06iy4.livekit.cloud',
    CHAT_LINEAR_BACKGROUND: ['#FFFFFF00', '#3C3C3C68', '#00000069'],
  },
  FLATLIST_KEYS: {
    PRODUCT_LIST: 'products_list_',
    ADDRESS_LIST: 'address_list_',
    VIDEO_LIST: 'video_list_',
    ORDER_LIST: 'order_list_',
  },
};
